version: '3.8'
services:
  # Infrastructure
  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs,s3
      - DEBUG=1
    volumes:
      - "./infra/localstack:/etc/localstack/init/ready.d"

  # Databases
  accounts-db:
    image: postgres:15
    environment:
      POSTGRES_DB: accounts_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  ledger-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ledger_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  notifications-db:
    image: postgres:15
    environment:
      POSTGRES_DB: notifications_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  # Services
  accounts-service:
    build: ./services/accounts
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@accounts-db:5432/accounts_dev
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=ca-central-1
      - SNS_TOPIC_ARN=arn:aws:sns:ca-central-1:000000000000:microbank-transactions-requested
    depends_on:
      - accounts-db
      - localstack
